StartupEvents.registry('block', event => {
  event.create('base:grass')
    .displayName('Grass')
    .solid(true)
    .runtimeOrder(0)
    .tintKey(true)
    .model('models/blocks/grass_block.json')
    .texture({ albedo: 'textures/blocks/grass.ppm', normal: 'textures/blocks/grass_normal.ppm', roughness: 'textures/blocks/grass_roughness.ppm', emissive: 'textures/blocks/grass_emissive.ppm' })
    .drops({ item: 'base:grass', count: 1 })

  event.create('base:dirt')
    .displayName('Dirt')
    .solid(true)
    .runtimeOrder(1)
    .color(0.549, 0.3804, 0.2157)
    .model('models/blocks/dirt.json')
    .texture('textures/blocks/dirt.ppm')
    .drops({ item: 'base:dirt', count: 1 })

  event.create('base:stone')
    .displayName('Stone')
    .solid(true)
    .runtimeOrder(3)
    .material('rock')
    .color(0.60, 0.60, 0.64)
    .model('models/blocks/stone.json')
    .texture('textures/blocks/stone.ppm')
    .drops({ item: 'base:stone', count: 1 })

  event.create('base:sand')
    .displayName('Sand')
    .solid(true)
    .color(0.85, 0.78, 0.50)
    .model('models/blocks/sand.json')
    .texture('textures/blocks/sand.ppm')
    .drops({ item: 'base:sand', count: 1 })

  event.create('base:oak_log')
    .displayName('Oak Log')
    .solid(true)
    .material('terrain')
    .color(0.52, 0.34, 0.18)
    .model('models/blocks/oak_log.json')
    .texture({ albedo: 'textures/blocks/oak_log_side.ppm' })
    .drops({ item: 'base:oak_log', count: 1 })

  event.create('base:oak_planks')
    .displayName('Oak Planks')
    .solid(true)
    .material('terrain')
    .color(0.72, 0.52, 0.28)
    .model('models/blocks/oak_planks.json')
    .texture('textures/blocks/oak_planks.ppm')
    .drops({ item: 'base:oak_planks', count: 1 })

  event.create('base:water')
    .displayName('Water')
    .solid(false)
    .runtimeOrder(2)
    .translucent(true)
    .material('liquid')
    .color(0.45, 0.65, 0.90)
    .opacity(0.55)
    .texture('textures/blocks/water.ppm')

  event.create('base:wheat')
    .displayName('Wheat')
    .solid(false)
    .material('plant')
    .color(0.55, 0.86, 0.36)
    .model('models/blocks/wheat_stage_0.json')
    .renderType('model')
    .texture('textures/blocks/wheat_stage_0.ppm')
    .drops({ item: 'base:wheat_seeds', count: 1 })
    .property('crop',               true)
    .property('tickInterval',       1)
    .property('maxAge',             3)
    .property('seedItem',           'base:wheat_seeds')
    .property('immatureSeedCount',  1)
    .property('matureSeedCount',    2)
    .property('produceItem',        'base:wheat')
    .property('produceCount',       1)
    .states({ age: { type: 'int', default: 0, min: 0, max: 3 } })
    .variants({
      'age=0': { model: 'models/blocks/wheat_stage_0.json' },
      'age=1': { model: 'models/blocks/wheat_stage_1.json' },
      'age=2': { model: 'models/blocks/wheat_stage_2.json' },
      'age=3': { model: 'models/blocks/wheat_stage_3.json' },
    })

  event.create('base:door')
    .displayName('Door')
    .solid(true)
    .color(0.55, 0.38, 0.24)
    .model('models/blocks/cube_test.json')
    .renderType('model')
    .drops({ item: 'base:door', count: 1 })

  event.create('base:crafting_table')
    .displayName('Crafting Table')
    .solid(true)
    .color(0.58, 0.39, 0.21)
    .model('models/blocks/crafting_table.json')
    .texture('textures/blocks/crafting_table_side.ppm')
    .drops({ item: 'base:crafting_table', count: 1 })
})

StartupEvents.registry('tag', event => {
  event.register('base:door')
  event.register({ id: 'base:flammable',   description: 'Block can catch fire' })
  event.register({ id: 'base:waterlogged', description: 'Block is submerged in water' })
  event.register({ id: 'base:plant',       description: 'Block is a plant' })
  event.register({ id: 'base:crop',        description: 'Block is a crop' })
  event.register({ id: 'base:door',        description: 'Block is a door' })
})
